### ISSUE TITLE
CONFIG_PATH environment is not being set properly in api_tests.py

### ISSUE THREAD

**Issue by shalperin** [oampo/pip-tuneful-project-template#2]
I assert that this line in api_tests.py is not functioning (although it is not inconceivable that this is my fault!):
`os.environ["CONFIG_PATH"] = "tuneful.config.TestingConfig"`

and that the nose tests will always fall through to the default value in this line of **init**.py
`config_path = os.environ.get("CONFIG_PATH", "tuneful.config.DevelopmentConfig")`  

This results in the development database being dropped after every test run.

My workaround in leu of a better fix is to remove the default to the `os.environ.get` call above (the second argument) and to run nose tests and run.py with the following shell scripts, or by manually exporting the right environment variable.

run.sh

```
export CONFIG_PATH=tuneful.config.DevelopmentConfig                                                                                                                          
python run.py 
```

run-tests.sh

```
export CONFIG_PATH=tuneful.config.TestingConfig                                                                                                                              
nosetests
```

**Comment by oampo** [comment]
Oh, this is full of fail.  Basically this setup relies on _api_tests.py_ being run before anything from Tuneful is, so the env variable is set correctly by the time `os.environ.get` is called.  That works fine if you run the code using `PYTHONPATH=. python tests/api_tests.py`, but it looks like the autodiscovery from nose imports from tuneful first, before the env variable is set.

I've never been happy with this bit of code.  Probably we should make the app/initialization into function which should fix the load order problems, but would require quite a bit of rewriting.  For a quick fix I'm tempted to just change the instructions to not use Nose.  Any objections to that?
