### ISSUE TITLE
"The buffer passed to decodeAudioData contains an unknown content type. EncodingError: The given encoding is not supported."

### ISSUE THREAD

**Issue by mdublin** [oampo/pip-tuneful-project-template#5]
Running Tuneful locally on my Mac OSX 10.10.5 with Python2.7 and can confirm via multiple checksumming that file handling is working properly (files are being "uploaded" from `Desktop` to the `uploads` directory inside the Tuneful app). When files are uploaded, they are populating in the songlist on the left-hand side of the UI.

However, when I attempt to select and play a file in the song list on either **Google Chrome version 44.0.2403.155 (64-bit)**, **Firefox 44.0.2**, and **Safari Version 9.0.3 (10601.4.4)**, no sound plays and the following error appears on the Console Log Firefox: 

```
The buffer passed to decodeAudioData contains an unknown content type. 
EncodingError: The given encoding is not supported.
```

And the following error appears in Chrome console log: 

`Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.`   and the`wavesurfer.min.js:2` is flagged 

Also, the animation with the rotating animal DJ guy only works/rotates in the Firefox version listed above, but does not work in Chrome or Safari versions listed above.

**Comment by oampo** [comment]
Hey!  Can you compare your code to what's at https://github.com/oampo/pip-tuneful-project.  I've just tested it out, and it seems to work find my end when playing an MP3 on Firefox 44 and Chromium 49.  I have a suspicion that it's not serving the file correctly your end.  You could take a look at the XHR for getting the song when you press play to make sure that it's actually receiving the data you think it is.

**Comment by oampo** [comment]
Edit: Just read through the thread on Slack and it looks like you've done a pretty thorough job of dispelling my suspicions about the file not being served correctly.  So, for reference I used [this MP3](https://ia700403.us.archive.org/18/items/12rec.064/12rec_-_The_Rare_Plants_Garden-01-Lato_M.mp3) for testing.  If that doesn't work and there are no obvious differences between the code then I'm a bit :confounded:.

**Comment by mdublin** [comment]
@oampo Thanks for looking into this, much appreciated. I'm getting the same error with that mp3 file you provided after uploading and trying to select and click the play button.  
![screenshot](https://cloud.githubusercontent.com/assets/6722001/13608638/9cf1a432-e523-11e5-98fd-10a1fe67dcbf.jpg)

While not exactly [an identical scenario](https://github.com/katspaugh/wavesurfer.js/issues/481), I am seeing that these errors have been seen before across both Chrome and Firefox. 

Regarding the Chrome console log error related specifically to wavesurfer.js, the [bitrate being too low](https://github.com/katspaugh/wavesurfer.js/issues/353) has been reported as causing this error, but that's not the problem with the audio files I'm testing this with. 

I'm assuming that `this.source.buffer=this.buffer` in `wavesurfer.min.js` is being interpreted as `this.source.buffer=undefined` but within the context of the app, it's unclear how to go about pinning down why nothing is being passed to `this.buffer`

**Comment by oampo** [comment]
Yeah, that's strange.  Can you push up your code to GitHub so I can try it on my end?  If it works here then we'll put it down to a platform-specific issue, and I'll watch out for any similar reports to try to narrow down what's causing it.  Thanks for taking the time on this!

**Comment by mdublin** [comment]
@oampo [Here it is](https://github.com/dubsoverflow/Tuneful.git)
Just note that the database configurations in `config.py` were changed to `localhost`, etc. 
Thanks for looking into this, hopefully I just made a stupid oversight and that's what's causing the issue.

**Comment by oampo** [comment]
Yeah, there were a couple of little things missing so the API was giving the wrong information to the frontend.

The `Song.asDictionary` method wasn't giving all of the information about the file to the frontend - it was missing the path variable.  To make this simpler, Song.asDictionary can use the `File.asDictionary` method:

``` python
    def as_dictionary(self):
        song = {
            "id" : self.id,
            "file": self.song_file.as_dictionary()
        }
        return song
```

Then `File.asDictionary` needs to use the correct key `name`, rather than `filename`:

``` python
    def as_dictionary(self):
        file = {
            "id" : self.id,
            "name" : self.filename,
            "path" : url_for("upload_file", filename=self.filename)
            }
        return file
```

And then with any luck you should see it start working.

**Comment by mdublin** [comment]
@oampo Awesome, thanks for the help! Much appreciated. 

![tunefulscreenshot](https://cloud.githubusercontent.com/assets/6722001/13688186/1c8321a0-e6ee-11e5-8f91-dc517a62371f.png)

**Comment by Y0QIN** [comment]
I meet the same problem in fifox with aac adts stream,but it work well in chrome.
